# Generated by Django 5.1.3 on 2024-11-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "heading",
                    models.CharField(
                        help_text="Введите заголовок",
                        max_length=50,
                        verbose_name="Заголовок",
                    ),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Введите содержимое поста"),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="blog/photo"),
                ),
                ("created_at", models.DateField(blank=True, null=True)),
                ("publication", models.BooleanField()),
                (
                    "views_counter",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Счетчик просмотров"
                    ),
                ),
            ],
            options={
                "verbose_name": "Пост",
                "verbose_name_plural": "Пост",
            },
        ),
    ]
