# Generated by Django 5.1.3 on 2024-11-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_product_created_at_alter_product_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateField(
                blank=True, help_text='Введите дату в формате "гггг-мм-дд"', null=True
            ),
        ),
    ]
