# Generated by Django 5.1.3 on 2024-12-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_product_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="publication_status",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
